<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PKUMAR" ignored="0" name="Marketplace Sanity Test1" tests="1" failures="1" timestamp="17 Aug 2017 11:17:38 GMT" time="8.607" errors="0">
  <testcase name="setPassword" time="0.037" classname="com.jamcracker.testcases.marketplace.TC002SetPassword">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at com.jamcracker.commonFunctions.marketplace.SetPassword.setPassword(SetPassword.java:40)
	at com.jamcracker.testcases.marketplace.TC002SetPassword.setPassword(TC002SetPassword.java:46)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- setPassword -->
</testsuite> <!-- Marketplace Sanity Test1 -->
